version: '3'
services:
    ytdsc:
        container_name: ytdsc
        image: docker.pkg.github.com/3ventic/ytdsc/ytdsc:latest
        restart: always
        stop_grace_period: 5s
        stop_signal: SIGINT
        ports:
            - '8000:8000/tcp'
